[package]
name = "awa-core"
version.workspace = true
edition.workspace = true

[features]
camera = ["dep:v4l"]

[dependencies]
v4l = { workspace = true, optional = true }
ort = { workspace = true }
ndarray = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
libc = { workspace = true }


[dev-dependencies]
tracing-subscriber = { workspace = true }
