[package]
name = "awa-daemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "awa-daemon"
path = "src/main.rs"

[dependencies]
awa-ipc = { path = "../awa-ipc" }
awa-core = { path = "../awa-core" }
clap = { workspace = true }
libc = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
